Add Docker commands task
jfrog/artifactory-vsts-extension pull request #345
Opened 2022-06-01 17:57 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-azure-devops-extension#testing) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----

2022-06-02 09:14 UTC, RobiNino requested changes
Haven't tried the UI, just looked at the code.

In addition to the comments I left on the code:
1. We usually use the build tool icon in task so we might want to change to the docker icon.
2. Please add tests.
3. Add docker.js to .eslintignore
4. Run `npm run format`
5. Don't forget to add a section to `overview.md` once you are done.

2022-06-02 09:14 UTC, RobiNino commented on tasks/JFrogDocker/docker.ts
> +    const inputWorkingDirectory: string = tl.getInput('workingDirectory', false) || '';
You can add a validation that verifies docker is installed (add declaration of isToolExists to utils.d.ts):
```
    // Validate docker exists on agent
    if (!utils.isToolExists('docker')) {
        tl.setResult(tl.TaskResult.Failed, 'Agent is missing required tool: docker.');
        return;
    }
```

2022-06-02 09:14 UTC, RobiNino commented on tasks/JFrogDocker/docker.ts
> +    const sourcePath: string = utils.determineCliWorkDir(defaultWorkDir, inputWorkingDirectory);
The js tasks that use this function also have a validation that it exists and is indeed a dir:
```
    if (!fs.existsSync(requiredWorkDir) || !fs.lstatSync(requiredWorkDir).isDirectory()) {
        tl.setResult(tl.TaskResult.Failed, "Provided 'Working folder with package.json': " + requiredWorkDir + ' neither exists nor a directory.');
        return;
    }
```
This is missing for the ts tasks for some reason. We might want to add the validation to the function itself to avoid the duplications.

2022-06-02 09:14 UTC, RobiNino commented on tasks/JFrogDocker/docker.ts
> +    switch (command) {
Missing native command support

2022-06-02 09:14 UTC, RobiNino commented on tasks/JFrogDocker/docker.ts
> +        case 'Pull':
Missing support for docker args, `skip-login`, `threads`, etc... each command with it's corresponding flags

2022-06-02 09:14 UTC, RobiNino commented on tasks/JFrogDocker/task.json
> +    "helpMarkDown": "[More Information](https://www.jfrog.com/confluence/display/JFROG/Artifactory+Azure+DevOps+Extension#ArtifactoryAzureDevOpsExtension-PushingandPullingDockerImagestoandfromArtifac
Point to the new documentation once this section is added there

2022-06-02 09:14 UTC, RobiNino commented on tasks/JFrogDocker/task.json
> +    "groups": [
The groups here are not used, please remove them.

2022-06-02 09:14 UTC, RobiNino commented on tasks/JFrogDocker/task.json
> +                "Scan": "Scan"
Add native command support

2022-06-04 07:20 UTC, eyalbe4 requested changes
Let's also add tests.

2022-06-04 07:20 UTC, eyalbe4 commented on buildScripts/build.js
> +            // We want to ignore files like .DS_Store may exist in TASKS_DIR
...like .DS_Store may exist in... --> ...like .DS_Store that may exist in...

2022-06-04 07:20 UTC, eyalbe4 commented on tasks/JFrogAudit/task.json
> +            "helpMarkDown": "Set to true if you'd like to receive licenses from Xray scanning."
Set to true if you'd like to receive licenses from Xray scanning.
-->
Set to true if you'd also like to show licenses information for the project dependencies.

2022-06-04 07:20 UTC, eyalbe4 commented on tasks/JFrogDocker/task.json
> +            "helpMarkDown": "Xray service to use in the command.",
Xray service to use in the command.
-->
Xray service to be used by this task. Used by the 'Scan' command only.

2022-06-04 07:20 UTC, eyalbe4 commented on tasks/JFrogDocker/task.json
> +            "required": true,
This field should be required only if the 'Push' or 'Pull' commands are used.
There's a chance the `visibleRule` takes care of that already, but I wasn't sure.

2022-06-04 07:20 UTC, eyalbe4 commented on tasks/JFrogDocker/task.json
> +            "required": true,
This field should be required only if the 'Scan' command is used.
The same goes for the other Xray specific fields.
There's a chance the `visibleRule` takes care of that already, but I wasn't sure.

2022-06-04 07:20 UTC, eyalbe4 commented on tasks/JFrogDocker/task.json
> +            "helpMarkDown": "Artifactory service to use in the command.",
Artifactory service to use in the command.
-->
Artifactory service to be used by this task. Used by the 'Pull' and 'Push' commands only.

2022-06-07 09:19 UTC, merged