Improve allowFailBuild option
jfrog/artifactory-vsts-extension pull request #388
Opened 2023-03-15 10:58 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-azure-devops-extension#testing) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----

2023-03-16 13:31 UTC, yahavi requested changes

2023-03-16 13:31 UTC, yahavi commented on tests/tests.ts
> +    }).timeout(400000); // 5 minutes
It is acually 6.6666667 minutes :)

2023-03-16 13:39 UTC, sverdlov93 commented on tests/tests.ts
> +    }).timeout(400000); // 5 minutes
changed to 360000

2023-03-19 16:00 UTC, eyalbe4 requested changes

2023-03-19 16:00 UTC, eyalbe4 commented on tasks/JFrogBuildScan/task.json
> +            "helpMarkDown": "Uncheck if you do not wish the command to return exit code 3, even if found a security violation that matches an Xray policy with 'Fail Build' rule."
Uncheck if you do not wish the command to return exit code 3, even if found a security violation that matches an Xray policy with 'Fail Build' rule.
-->
Unset if you don't wish the audit process to exit with code 3, if a violation matching an Xray policy is found, and the policy includes a 'Fail Build' rule.

Let's make this change in the other two `task.json` files in this PR.

2023-03-19 16:00 UTC, eyalbe4 commented on tasks/JFrogAudit/task.json
> +            "visibleRule": "watchesSource!=none",
Shouldn't this condition include `project` as well? A policy which includes `Fail build` can also be associated with a Project and not just a Watch.

Also notice that this visibility condition should be modified in one of the other two `task.json` files. One of the `task.json` is missing a visibility condition altogether.

2023-03-19 16:00 UTC, eyalbe4 commented on tasks/JFrogBuildScan/task.json
> +            "helpMarkDown": "Set to true if you'd like to receive an additional view of all vulnerabilities, regardless of the policy configured in Xray. (This functionality requires version 3.40.0 o
Set to true if you'd like to receive an additional view of all vulnerabilities, regardless of the policy configured in Xray. (This functionality requires version 3.40.0 or above of JFrog Xray)
-->
Set to true if you'd like to see an additional view with all vulnerabilities, regardless of the policy configured in Xray. (This functionality requires version 3.40.0 or above of JFrog Xray)

2023-03-19 16:21 UTC, sverdlov93 commented on tasks/JFrogAudit/task.json
> +            "visibleRule": "watchesSource!=none",
@eyalbe4 
1. watchesSource includes watches/repopath/projects 
2. it's on purpose, the build-scan task is a context command by design. it's always connected to a watch

2023-03-19 17:34 UTC, merged