Update JFrog CLI to 2.48.0 and update dependencies
jfrog/artifactory-vsts-extension pull request #451
Opened 2023-09-27 12:09 UTC by sverdlov93

- [ ] All [tests](https://github.com/jfrog/jfrog-azure-devops-extension#testing) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] This pull request is on the dev branch.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----

2023-10-05 07:50 UTC, ashokm commented
Looks like newer versions have been [released](https://github.com/jfrog/jfrog-cli/releases).
Please update to the latest released version (**2.49.1** at time of writing).

2023-10-05 08:00 UTC, sverdlov93 commented
> Looks like newer versions have been [released](https://github.com/jfrog/jfrog-cli/releases). Please update to the latest released version (**2.49.1** at time of writing).
@ashokm 
Yes, that's the reason we waited. We will release it soon.

2023-11-14 10:36 UTC, ashokm commented
Are there any ETAs on a release?

2023-12-07 15:50 UTC, yahavi requested changes

2023-12-07 15:50 UTC, yahavi commented on buildScripts/publish-private.sh
> +vsixSize="$(du -m -- *.vsix | awk '{print $1}')"
Ensure that only the first one tooked
```suggestion
vsixSize="$(du -m -- *.vsix | awk '{print $1}' | head -1)"
```

2023-12-14 09:37 UTC, merged