Support .NET custom command
jfrog/artifactory-vsts-extension pull request #497
Opened 2024-05-27 10:20 UTC by RobiNino

- [x] All [tests](https://github.com/jfrog/jfrog-azure-devops-extension#testing) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----
Following #468.
![image](https://github.com/jfrog/jfrog-azure-devops-extension/assets/43318887/88659151-6ac9-4d2c-a104-605b1a40f9d4)

2024-06-09 06:02 UTC, yahavi requested changes

2024-06-09 06:02 UTC, yahavi commented on tasks/JFrogDotnet/task.json
> +            "required": true,
Shoul'd it really be required?

2024-06-09 06:02 UTC, yahavi commented on tasks/JFrogDotnet/task.json
> +            "defaultValue": "",
```suggestion
```

2024-06-09 06:02 UTC, yahavi commented on tasks/JFrogDotnet/task.json
> +            "visibleRule": "command=restore || command=custom"
If you agree, let's do this also is the other fields below
```suggestion
            "visibleRule": "command = restore || command = custom"
```

2024-06-09 06:07 UTC, yahavi commented
It might also be challenging to grasp the difference between "custom command" and "arguments" without providing examples of each.

2024-06-13 09:23 UTC, RobiNino commented on tasks/JFrogDotnet/task.json
> +            "required": true,
If the user chose to provide a custom command, then the custom command is required. Don't you agree?

2024-06-13 11:09 UTC, yahavi commented on tasks/JFrogDotnet/task.json
> +            "required": true,
Agree. Right.

2024-06-18 12:19 UTC, RobiNino commented on tasks/JFrogDotnet/task.json
> +            "visibleRule": "command=restore || command=custom"
I changed them on purpose, I find it way more readable. Why don't you like this change?

2024-06-18 14:09 UTC, merged