Added support for Node10 adn Node20
jfrog/artifactory-vsts-extension pull request #518
Opened 2024-11-05 20:00 UTC by hanankem

- [] All [tests](https://github.com/jfrog/jfrog-azure-devops-extension#testing) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----

2024-11-05 20:17 UTC, eyalbe4 requested changes

2024-11-05 20:17 UTC, eyalbe4 commented on tasks/JFrogAudit/task.json
>          "Node16": {
I'm actually not sure Node 16 is needed here.
Perhaps it best to have only Node 10 and Node 20.

2024-11-06 07:00 UTC, hanankem commented on tasks/JFrogAudit/task.json
>          "Node16": {
I agree, I will remote Node 16

2024-11-06 07:05 UTC, hanankem commented
I have read the CLA Document and I hereby sign the CLA

2024-11-06 07:57 UTC, johnpp143 reviewed
"Node20_1" may not be required, as azure tasks globally use node 20

2024-11-06 10:05 UTC, merged